###
GET http://localhost:8080/regions

###
GET http://localhost:8080/regions?page=1&size=30

###
GET http://localhost:8080/regions/61c45c68906f02a66b345413

###
DELETE http://localhost:8080/regions/delete/61e1d0f5f303625bf6928e52

###
GET http://localhost:8080/peoples

###
GET http://localhost:8080/peoples/61ef991168e1c352d15addfd

###
GET http://localhost:8080/basins

###
GET http://localhost:8080/fps